### ISSUE TITLE
Custom render script crashes game on BLU Zoey Smart

### ISSUE THREAD

**Issue by subsoap** [kaiostech/defold-sample-app#2]
I got a BLU Zoey Smart for testing and game crashed on load until I disabled the custom render script.

If it's possible to detect KaiOS device / memory, it may be necessary to disable custom render script features on lower end devices.

I don't know if Navigator.deviceMemory is possible to use in this case. Is there a feature do get this info?

**Comment by subsoap** [comment]
> navigator.getFeature('hardware.memory') returns a Promise that should resolve to either 0.25 or 0.5 on KaiOS
> You need the feature-detection permission, which is only available to privileged apps

So solution may be to detect 0.25 and disable the custom rendering in that case. I don't have a 0.5 device atm so not sure if it crashes too though. Someone else needs to test this.

**Comment by wulaiyin789** [comment]
Sorry for the late reply.

It seems not every 256MB device can run perfectly due to memory usage and the app sometimes can run without crashing. Do you mean that using the default render script is a better solution? If this is the case, we can change back to 'default.render' to avoid the cashing.

It is working without issue on 512MB as it has better memory usage, so it doesn't matter either enable or disable the custom render script.

**Comment by subsoap** [comment]
Yes, the default render script worked to not crash on launch with your example project on 256MB device.

**Comment by wulaiyin789** [comment]
I tested your solution. The default render script is working fine.

We can replace this line in the `game.project`
`render = /render/roids_test.renderc`
to
`render = /builtins/render/default.renderc`

It sounds good to me.
